/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HireReactDeveloperRouteImport } from './routes/hire-react-developer'
import { Route as HireNodejsDeveloperRouteImport } from './routes/hire-nodejs-developer'
import { Route as HireNextjsDeveloperRouteImport } from './routes/hire-nextjs-developer'
import { Route as HireMernDeveloperRouteImport } from './routes/hire-mern-developer'
import { Route as HireBackendDeveloperRouteImport } from './routes/hire-backend-developer'
import { Route as HireAiDeveloperRouteImport } from './routes/hire-ai-developer'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ServicesReactDevelopmentRouteImport } from './routes/services/react-development'
import { Route as ServicesNodejsDevelopmentRouteImport } from './routes/services/nodejs-development'
import { Route as ServicesNextjsDevelopmentRouteImport } from './routes/services/nextjs-development'
import { Route as ServicesMvpDevelopmentRouteImport } from './routes/services/mvp-development'
import { Route as ServicesMernDevelopmentRouteImport } from './routes/services/mern-development'
import { Route as ServicesFullStackDevelopmentRouteImport } from './routes/services/full-stack-development'
import { Route as ServicesCustomSoftwareDevelopmentRouteImport } from './routes/services/custom-software-development'
import { Route as ServicesBackendDevelopmentRouteImport } from './routes/services/backend-development'
import { Route as ServicesAiDevelopmentRouteImport } from './routes/services/ai-development'
import { Route as IndustriesWorkforceManagementSoftwareRouteImport } from './routes/industries/workforce-management-software'
import { Route as IndustriesRenewableEnergySoftwareRouteImport } from './routes/industries/renewable-energy-software'
import { Route as IndustriesOilGasSoftwareRouteImport } from './routes/industries/oil-gas-software'
import { Route as IndustriesMiningSoftwareRouteImport } from './routes/industries/mining-software'
import { Route as IndustriesMarineShippingSoftwareRouteImport } from './routes/industries/marine-shipping-software'
import { Route as IndustriesManufacturingSoftwareRouteImport } from './routes/industries/manufacturing-software'
import { Route as IndustriesLogisticsSupplyChainSoftwareRouteImport } from './routes/industries/logistics-supply-chain-software'
import { Route as IndustriesHseComplianceSoftwareRouteImport } from './routes/industries/hse-compliance-software'
import { Route as IndustriesFieldServiceManagementSoftwareRouteImport } from './routes/industries/field-service-management-software'
import { Route as IndustriesFacilityManagementSoftwareRouteImport } from './routes/industries/facility-management-software'
import { Route as IndustriesEpcEngineeringSoftwareRouteImport } from './routes/industries/epc-engineering-software'
import { Route as IndustriesConstructionSoftwareRouteImport } from './routes/industries/construction-software'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HireReactDeveloperRoute = HireReactDeveloperRouteImport.update({
  id: '/hire-react-developer',
  path: '/hire-react-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const HireNodejsDeveloperRoute = HireNodejsDeveloperRouteImport.update({
  id: '/hire-nodejs-developer',
  path: '/hire-nodejs-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const HireNextjsDeveloperRoute = HireNextjsDeveloperRouteImport.update({
  id: '/hire-nextjs-developer',
  path: '/hire-nextjs-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const HireMernDeveloperRoute = HireMernDeveloperRouteImport.update({
  id: '/hire-mern-developer',
  path: '/hire-mern-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const HireBackendDeveloperRoute = HireBackendDeveloperRouteImport.update({
  id: '/hire-backend-developer',
  path: '/hire-backend-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const HireAiDeveloperRoute = HireAiDeveloperRouteImport.update({
  id: '/hire-ai-developer',
  path: '/hire-ai-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ServicesReactDevelopmentRoute =
  ServicesReactDevelopmentRouteImport.update({
    id: '/react-development',
    path: '/react-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesNodejsDevelopmentRoute =
  ServicesNodejsDevelopmentRouteImport.update({
    id: '/nodejs-development',
    path: '/nodejs-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesNextjsDevelopmentRoute =
  ServicesNextjsDevelopmentRouteImport.update({
    id: '/nextjs-development',
    path: '/nextjs-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesMvpDevelopmentRoute = ServicesMvpDevelopmentRouteImport.update({
  id: '/mvp-development',
  path: '/mvp-development',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMernDevelopmentRoute = ServicesMernDevelopmentRouteImport.update({
  id: '/mern-development',
  path: '/mern-development',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFullStackDevelopmentRoute =
  ServicesFullStackDevelopmentRouteImport.update({
    id: '/full-stack-development',
    path: '/full-stack-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCustomSoftwareDevelopmentRoute =
  ServicesCustomSoftwareDevelopmentRouteImport.update({
    id: '/custom-software-development',
    path: '/custom-software-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesBackendDevelopmentRoute =
  ServicesBackendDevelopmentRouteImport.update({
    id: '/backend-development',
    path: '/backend-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAiDevelopmentRoute = ServicesAiDevelopmentRouteImport.update({
  id: '/ai-development',
  path: '/ai-development',
  getParentRoute: () => ServicesRoute,
} as any)
const IndustriesWorkforceManagementSoftwareRoute =
  IndustriesWorkforceManagementSoftwareRouteImport.update({
    id: '/workforce-management-software',
    path: '/workforce-management-software',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesRenewableEnergySoftwareRoute =
  IndustriesRenewableEnergySoftwareRouteImport.update({
    id: '/renewable-energy-software',
    path: '/renewable-energy-software',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesOilGasSoftwareRoute =
  IndustriesOilGasSoftwareRouteImport.update({
    id: '/oil-gas-software',
    path: '/oil-gas-software',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesMiningSoftwareRoute =
  IndustriesMiningSoftwareRouteImport.update({
    id: '/mining-software',
    path: '/mining-software',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesMarineShippingSoftwareRoute =
  IndustriesMarineShippingSoftwareRouteImport.update({
    id: '/marine-shipping-software',
    path: '/marine-shipping-software',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesManufacturingSoftwareRoute =
  IndustriesManufacturingSoftwareRouteImport.update({
    id: '/manufacturing-software',
    path: '/manufacturing-software',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesLogisticsSupplyChainSoftwareRoute =
  IndustriesLogisticsSupplyChainSoftwareRouteImport.update({
    id: '/logistics-supply-chain-software',
    path: '/logistics-supply-chain-software',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesHseComplianceSoftwareRoute =
  IndustriesHseComplianceSoftwareRouteImport.update({
    id: '/hse-compliance-software',
    path: '/hse-compliance-software',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesFieldServiceManagementSoftwareRoute =
  IndustriesFieldServiceManagementSoftwareRouteImport.update({
    id: '/field-service-management-software',
    path: '/field-service-management-software',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesFacilityManagementSoftwareRoute =
  IndustriesFacilityManagementSoftwareRouteImport.update({
    id: '/facility-management-software',
    path: '/facility-management-software',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesEpcEngineeringSoftwareRoute =
  IndustriesEpcEngineeringSoftwareRouteImport.update({
    id: '/epc-engineering-software',
    path: '/epc-engineering-software',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesConstructionSoftwareRoute =
  IndustriesConstructionSoftwareRouteImport.update({
    id: '/construction-software',
    path: '/construction-software',
    getParentRoute: () => IndustriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/hire-ai-developer': typeof HireAiDeveloperRoute
  '/hire-backend-developer': typeof HireBackendDeveloperRoute
  '/hire-mern-developer': typeof HireMernDeveloperRoute
  '/hire-nextjs-developer': typeof HireNextjsDeveloperRoute
  '/hire-nodejs-developer': typeof HireNodejsDeveloperRoute
  '/hire-react-developer': typeof HireReactDeveloperRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/industries/construction-software': typeof IndustriesConstructionSoftwareRoute
  '/industries/epc-engineering-software': typeof IndustriesEpcEngineeringSoftwareRoute
  '/industries/facility-management-software': typeof IndustriesFacilityManagementSoftwareRoute
  '/industries/field-service-management-software': typeof IndustriesFieldServiceManagementSoftwareRoute
  '/industries/hse-compliance-software': typeof IndustriesHseComplianceSoftwareRoute
  '/industries/logistics-supply-chain-software': typeof IndustriesLogisticsSupplyChainSoftwareRoute
  '/industries/manufacturing-software': typeof IndustriesManufacturingSoftwareRoute
  '/industries/marine-shipping-software': typeof IndustriesMarineShippingSoftwareRoute
  '/industries/mining-software': typeof IndustriesMiningSoftwareRoute
  '/industries/oil-gas-software': typeof IndustriesOilGasSoftwareRoute
  '/industries/renewable-energy-software': typeof IndustriesRenewableEnergySoftwareRoute
  '/industries/workforce-management-software': typeof IndustriesWorkforceManagementSoftwareRoute
  '/services/ai-development': typeof ServicesAiDevelopmentRoute
  '/services/backend-development': typeof ServicesBackendDevelopmentRoute
  '/services/custom-software-development': typeof ServicesCustomSoftwareDevelopmentRoute
  '/services/full-stack-development': typeof ServicesFullStackDevelopmentRoute
  '/services/mern-development': typeof ServicesMernDevelopmentRoute
  '/services/mvp-development': typeof ServicesMvpDevelopmentRoute
  '/services/nextjs-development': typeof ServicesNextjsDevelopmentRoute
  '/services/nodejs-development': typeof ServicesNodejsDevelopmentRoute
  '/services/react-development': typeof ServicesReactDevelopmentRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hire-ai-developer': typeof HireAiDeveloperRoute
  '/hire-backend-developer': typeof HireBackendDeveloperRoute
  '/hire-mern-developer': typeof HireMernDeveloperRoute
  '/hire-nextjs-developer': typeof HireNextjsDeveloperRoute
  '/hire-nodejs-developer': typeof HireNodejsDeveloperRoute
  '/hire-react-developer': typeof HireReactDeveloperRoute
  '/services': typeof ServicesRouteWithChildren
  '/industries/construction-software': typeof IndustriesConstructionSoftwareRoute
  '/industries/epc-engineering-software': typeof IndustriesEpcEngineeringSoftwareRoute
  '/industries/facility-management-software': typeof IndustriesFacilityManagementSoftwareRoute
  '/industries/field-service-management-software': typeof IndustriesFieldServiceManagementSoftwareRoute
  '/industries/hse-compliance-software': typeof IndustriesHseComplianceSoftwareRoute
  '/industries/logistics-supply-chain-software': typeof IndustriesLogisticsSupplyChainSoftwareRoute
  '/industries/manufacturing-software': typeof IndustriesManufacturingSoftwareRoute
  '/industries/marine-shipping-software': typeof IndustriesMarineShippingSoftwareRoute
  '/industries/mining-software': typeof IndustriesMiningSoftwareRoute
  '/industries/oil-gas-software': typeof IndustriesOilGasSoftwareRoute
  '/industries/renewable-energy-software': typeof IndustriesRenewableEnergySoftwareRoute
  '/industries/workforce-management-software': typeof IndustriesWorkforceManagementSoftwareRoute
  '/services/ai-development': typeof ServicesAiDevelopmentRoute
  '/services/backend-development': typeof ServicesBackendDevelopmentRoute
  '/services/custom-software-development': typeof ServicesCustomSoftwareDevelopmentRoute
  '/services/full-stack-development': typeof ServicesFullStackDevelopmentRoute
  '/services/mern-development': typeof ServicesMernDevelopmentRoute
  '/services/mvp-development': typeof ServicesMvpDevelopmentRoute
  '/services/nextjs-development': typeof ServicesNextjsDevelopmentRoute
  '/services/nodejs-development': typeof ServicesNodejsDevelopmentRoute
  '/services/react-development': typeof ServicesReactDevelopmentRoute
  '/blog': typeof BlogIndexRoute
  '/industries': typeof IndustriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/hire-ai-developer': typeof HireAiDeveloperRoute
  '/hire-backend-developer': typeof HireBackendDeveloperRoute
  '/hire-mern-developer': typeof HireMernDeveloperRoute
  '/hire-nextjs-developer': typeof HireNextjsDeveloperRoute
  '/hire-nodejs-developer': typeof HireNodejsDeveloperRoute
  '/hire-react-developer': typeof HireReactDeveloperRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/industries/construction-software': typeof IndustriesConstructionSoftwareRoute
  '/industries/epc-engineering-software': typeof IndustriesEpcEngineeringSoftwareRoute
  '/industries/facility-management-software': typeof IndustriesFacilityManagementSoftwareRoute
  '/industries/field-service-management-software': typeof IndustriesFieldServiceManagementSoftwareRoute
  '/industries/hse-compliance-software': typeof IndustriesHseComplianceSoftwareRoute
  '/industries/logistics-supply-chain-software': typeof IndustriesLogisticsSupplyChainSoftwareRoute
  '/industries/manufacturing-software': typeof IndustriesManufacturingSoftwareRoute
  '/industries/marine-shipping-software': typeof IndustriesMarineShippingSoftwareRoute
  '/industries/mining-software': typeof IndustriesMiningSoftwareRoute
  '/industries/oil-gas-software': typeof IndustriesOilGasSoftwareRoute
  '/industries/renewable-energy-software': typeof IndustriesRenewableEnergySoftwareRoute
  '/industries/workforce-management-software': typeof IndustriesWorkforceManagementSoftwareRoute
  '/services/ai-development': typeof ServicesAiDevelopmentRoute
  '/services/backend-development': typeof ServicesBackendDevelopmentRoute
  '/services/custom-software-development': typeof ServicesCustomSoftwareDevelopmentRoute
  '/services/full-stack-development': typeof ServicesFullStackDevelopmentRoute
  '/services/mern-development': typeof ServicesMernDevelopmentRoute
  '/services/mvp-development': typeof ServicesMvpDevelopmentRoute
  '/services/nextjs-development': typeof ServicesNextjsDevelopmentRoute
  '/services/nodejs-development': typeof ServicesNodejsDevelopmentRoute
  '/services/react-development': typeof ServicesReactDevelopmentRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/hire-ai-developer'
    | '/hire-backend-developer'
    | '/hire-mern-developer'
    | '/hire-nextjs-developer'
    | '/hire-nodejs-developer'
    | '/hire-react-developer'
    | '/industries'
    | '/services'
    | '/industries/construction-software'
    | '/industries/epc-engineering-software'
    | '/industries/facility-management-software'
    | '/industries/field-service-management-software'
    | '/industries/hse-compliance-software'
    | '/industries/logistics-supply-chain-software'
    | '/industries/manufacturing-software'
    | '/industries/marine-shipping-software'
    | '/industries/mining-software'
    | '/industries/oil-gas-software'
    | '/industries/renewable-energy-software'
    | '/industries/workforce-management-software'
    | '/services/ai-development'
    | '/services/backend-development'
    | '/services/custom-software-development'
    | '/services/full-stack-development'
    | '/services/mern-development'
    | '/services/mvp-development'
    | '/services/nextjs-development'
    | '/services/nodejs-development'
    | '/services/react-development'
    | '/blog/'
    | '/industries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hire-ai-developer'
    | '/hire-backend-developer'
    | '/hire-mern-developer'
    | '/hire-nextjs-developer'
    | '/hire-nodejs-developer'
    | '/hire-react-developer'
    | '/services'
    | '/industries/construction-software'
    | '/industries/epc-engineering-software'
    | '/industries/facility-management-software'
    | '/industries/field-service-management-software'
    | '/industries/hse-compliance-software'
    | '/industries/logistics-supply-chain-software'
    | '/industries/manufacturing-software'
    | '/industries/marine-shipping-software'
    | '/industries/mining-software'
    | '/industries/oil-gas-software'
    | '/industries/renewable-energy-software'
    | '/industries/workforce-management-software'
    | '/services/ai-development'
    | '/services/backend-development'
    | '/services/custom-software-development'
    | '/services/full-stack-development'
    | '/services/mern-development'
    | '/services/mvp-development'
    | '/services/nextjs-development'
    | '/services/nodejs-development'
    | '/services/react-development'
    | '/blog'
    | '/industries'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/hire-ai-developer'
    | '/hire-backend-developer'
    | '/hire-mern-developer'
    | '/hire-nextjs-developer'
    | '/hire-nodejs-developer'
    | '/hire-react-developer'
    | '/industries'
    | '/services'
    | '/industries/construction-software'
    | '/industries/epc-engineering-software'
    | '/industries/facility-management-software'
    | '/industries/field-service-management-software'
    | '/industries/hse-compliance-software'
    | '/industries/logistics-supply-chain-software'
    | '/industries/manufacturing-software'
    | '/industries/marine-shipping-software'
    | '/industries/mining-software'
    | '/industries/oil-gas-software'
    | '/industries/renewable-energy-software'
    | '/industries/workforce-management-software'
    | '/services/ai-development'
    | '/services/backend-development'
    | '/services/custom-software-development'
    | '/services/full-stack-development'
    | '/services/mern-development'
    | '/services/mvp-development'
    | '/services/nextjs-development'
    | '/services/nodejs-development'
    | '/services/react-development'
    | '/blog/'
    | '/industries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  HireAiDeveloperRoute: typeof HireAiDeveloperRoute
  HireBackendDeveloperRoute: typeof HireBackendDeveloperRoute
  HireMernDeveloperRoute: typeof HireMernDeveloperRoute
  HireNextjsDeveloperRoute: typeof HireNextjsDeveloperRoute
  HireNodejsDeveloperRoute: typeof HireNodejsDeveloperRoute
  HireReactDeveloperRoute: typeof HireReactDeveloperRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-react-developer': {
      id: '/hire-react-developer'
      path: '/hire-react-developer'
      fullPath: '/hire-react-developer'
      preLoaderRoute: typeof HireReactDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-nodejs-developer': {
      id: '/hire-nodejs-developer'
      path: '/hire-nodejs-developer'
      fullPath: '/hire-nodejs-developer'
      preLoaderRoute: typeof HireNodejsDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-nextjs-developer': {
      id: '/hire-nextjs-developer'
      path: '/hire-nextjs-developer'
      fullPath: '/hire-nextjs-developer'
      preLoaderRoute: typeof HireNextjsDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-mern-developer': {
      id: '/hire-mern-developer'
      path: '/hire-mern-developer'
      fullPath: '/hire-mern-developer'
      preLoaderRoute: typeof HireMernDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-backend-developer': {
      id: '/hire-backend-developer'
      path: '/hire-backend-developer'
      fullPath: '/hire-backend-developer'
      preLoaderRoute: typeof HireBackendDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-ai-developer': {
      id: '/hire-ai-developer'
      path: '/hire-ai-developer'
      fullPath: '/hire-ai-developer'
      preLoaderRoute: typeof HireAiDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/services/react-development': {
      id: '/services/react-development'
      path: '/react-development'
      fullPath: '/services/react-development'
      preLoaderRoute: typeof ServicesReactDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/nodejs-development': {
      id: '/services/nodejs-development'
      path: '/nodejs-development'
      fullPath: '/services/nodejs-development'
      preLoaderRoute: typeof ServicesNodejsDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/nextjs-development': {
      id: '/services/nextjs-development'
      path: '/nextjs-development'
      fullPath: '/services/nextjs-development'
      preLoaderRoute: typeof ServicesNextjsDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mvp-development': {
      id: '/services/mvp-development'
      path: '/mvp-development'
      fullPath: '/services/mvp-development'
      preLoaderRoute: typeof ServicesMvpDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mern-development': {
      id: '/services/mern-development'
      path: '/mern-development'
      fullPath: '/services/mern-development'
      preLoaderRoute: typeof ServicesMernDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/full-stack-development': {
      id: '/services/full-stack-development'
      path: '/full-stack-development'
      fullPath: '/services/full-stack-development'
      preLoaderRoute: typeof ServicesFullStackDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/custom-software-development': {
      id: '/services/custom-software-development'
      path: '/custom-software-development'
      fullPath: '/services/custom-software-development'
      preLoaderRoute: typeof ServicesCustomSoftwareDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/backend-development': {
      id: '/services/backend-development'
      path: '/backend-development'
      fullPath: '/services/backend-development'
      preLoaderRoute: typeof ServicesBackendDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-development': {
      id: '/services/ai-development'
      path: '/ai-development'
      fullPath: '/services/ai-development'
      preLoaderRoute: typeof ServicesAiDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/industries/workforce-management-software': {
      id: '/industries/workforce-management-software'
      path: '/workforce-management-software'
      fullPath: '/industries/workforce-management-software'
      preLoaderRoute: typeof IndustriesWorkforceManagementSoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/renewable-energy-software': {
      id: '/industries/renewable-energy-software'
      path: '/renewable-energy-software'
      fullPath: '/industries/renewable-energy-software'
      preLoaderRoute: typeof IndustriesRenewableEnergySoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/oil-gas-software': {
      id: '/industries/oil-gas-software'
      path: '/oil-gas-software'
      fullPath: '/industries/oil-gas-software'
      preLoaderRoute: typeof IndustriesOilGasSoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/mining-software': {
      id: '/industries/mining-software'
      path: '/mining-software'
      fullPath: '/industries/mining-software'
      preLoaderRoute: typeof IndustriesMiningSoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/marine-shipping-software': {
      id: '/industries/marine-shipping-software'
      path: '/marine-shipping-software'
      fullPath: '/industries/marine-shipping-software'
      preLoaderRoute: typeof IndustriesMarineShippingSoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/manufacturing-software': {
      id: '/industries/manufacturing-software'
      path: '/manufacturing-software'
      fullPath: '/industries/manufacturing-software'
      preLoaderRoute: typeof IndustriesManufacturingSoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/logistics-supply-chain-software': {
      id: '/industries/logistics-supply-chain-software'
      path: '/logistics-supply-chain-software'
      fullPath: '/industries/logistics-supply-chain-software'
      preLoaderRoute: typeof IndustriesLogisticsSupplyChainSoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/hse-compliance-software': {
      id: '/industries/hse-compliance-software'
      path: '/hse-compliance-software'
      fullPath: '/industries/hse-compliance-software'
      preLoaderRoute: typeof IndustriesHseComplianceSoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/field-service-management-software': {
      id: '/industries/field-service-management-software'
      path: '/field-service-management-software'
      fullPath: '/industries/field-service-management-software'
      preLoaderRoute: typeof IndustriesFieldServiceManagementSoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/facility-management-software': {
      id: '/industries/facility-management-software'
      path: '/facility-management-software'
      fullPath: '/industries/facility-management-software'
      preLoaderRoute: typeof IndustriesFacilityManagementSoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/epc-engineering-software': {
      id: '/industries/epc-engineering-software'
      path: '/epc-engineering-software'
      fullPath: '/industries/epc-engineering-software'
      preLoaderRoute: typeof IndustriesEpcEngineeringSoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/construction-software': {
      id: '/industries/construction-software'
      path: '/construction-software'
      fullPath: '/industries/construction-software'
      preLoaderRoute: typeof IndustriesConstructionSoftwareRouteImport
      parentRoute: typeof IndustriesRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface IndustriesRouteChildren {
  IndustriesConstructionSoftwareRoute: typeof IndustriesConstructionSoftwareRoute
  IndustriesEpcEngineeringSoftwareRoute: typeof IndustriesEpcEngineeringSoftwareRoute
  IndustriesFacilityManagementSoftwareRoute: typeof IndustriesFacilityManagementSoftwareRoute
  IndustriesFieldServiceManagementSoftwareRoute: typeof IndustriesFieldServiceManagementSoftwareRoute
  IndustriesHseComplianceSoftwareRoute: typeof IndustriesHseComplianceSoftwareRoute
  IndustriesLogisticsSupplyChainSoftwareRoute: typeof IndustriesLogisticsSupplyChainSoftwareRoute
  IndustriesManufacturingSoftwareRoute: typeof IndustriesManufacturingSoftwareRoute
  IndustriesMarineShippingSoftwareRoute: typeof IndustriesMarineShippingSoftwareRoute
  IndustriesMiningSoftwareRoute: typeof IndustriesMiningSoftwareRoute
  IndustriesOilGasSoftwareRoute: typeof IndustriesOilGasSoftwareRoute
  IndustriesRenewableEnergySoftwareRoute: typeof IndustriesRenewableEnergySoftwareRoute
  IndustriesWorkforceManagementSoftwareRoute: typeof IndustriesWorkforceManagementSoftwareRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesConstructionSoftwareRoute: IndustriesConstructionSoftwareRoute,
  IndustriesEpcEngineeringSoftwareRoute: IndustriesEpcEngineeringSoftwareRoute,
  IndustriesFacilityManagementSoftwareRoute:
    IndustriesFacilityManagementSoftwareRoute,
  IndustriesFieldServiceManagementSoftwareRoute:
    IndustriesFieldServiceManagementSoftwareRoute,
  IndustriesHseComplianceSoftwareRoute: IndustriesHseComplianceSoftwareRoute,
  IndustriesLogisticsSupplyChainSoftwareRoute:
    IndustriesLogisticsSupplyChainSoftwareRoute,
  IndustriesManufacturingSoftwareRoute: IndustriesManufacturingSoftwareRoute,
  IndustriesMarineShippingSoftwareRoute: IndustriesMarineShippingSoftwareRoute,
  IndustriesMiningSoftwareRoute: IndustriesMiningSoftwareRoute,
  IndustriesOilGasSoftwareRoute: IndustriesOilGasSoftwareRoute,
  IndustriesRenewableEnergySoftwareRoute:
    IndustriesRenewableEnergySoftwareRoute,
  IndustriesWorkforceManagementSoftwareRoute:
    IndustriesWorkforceManagementSoftwareRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesAiDevelopmentRoute: typeof ServicesAiDevelopmentRoute
  ServicesBackendDevelopmentRoute: typeof ServicesBackendDevelopmentRoute
  ServicesCustomSoftwareDevelopmentRoute: typeof ServicesCustomSoftwareDevelopmentRoute
  ServicesFullStackDevelopmentRoute: typeof ServicesFullStackDevelopmentRoute
  ServicesMernDevelopmentRoute: typeof ServicesMernDevelopmentRoute
  ServicesMvpDevelopmentRoute: typeof ServicesMvpDevelopmentRoute
  ServicesNextjsDevelopmentRoute: typeof ServicesNextjsDevelopmentRoute
  ServicesNodejsDevelopmentRoute: typeof ServicesNodejsDevelopmentRoute
  ServicesReactDevelopmentRoute: typeof ServicesReactDevelopmentRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAiDevelopmentRoute: ServicesAiDevelopmentRoute,
  ServicesBackendDevelopmentRoute: ServicesBackendDevelopmentRoute,
  ServicesCustomSoftwareDevelopmentRoute:
    ServicesCustomSoftwareDevelopmentRoute,
  ServicesFullStackDevelopmentRoute: ServicesFullStackDevelopmentRoute,
  ServicesMernDevelopmentRoute: ServicesMernDevelopmentRoute,
  ServicesMvpDevelopmentRoute: ServicesMvpDevelopmentRoute,
  ServicesNextjsDevelopmentRoute: ServicesNextjsDevelopmentRoute,
  ServicesNodejsDevelopmentRoute: ServicesNodejsDevelopmentRoute,
  ServicesReactDevelopmentRoute: ServicesReactDevelopmentRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  HireAiDeveloperRoute: HireAiDeveloperRoute,
  HireBackendDeveloperRoute: HireBackendDeveloperRoute,
  HireMernDeveloperRoute: HireMernDeveloperRoute,
  HireNextjsDeveloperRoute: HireNextjsDeveloperRoute,
  HireNodejsDeveloperRoute: HireNodejsDeveloperRoute,
  HireReactDeveloperRoute: HireReactDeveloperRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
